### ISSUE TITLE
the console drops an error when i use /homelist please help i loved the plugin

### ISSUE THREAD

**Issue by OnlyBizzclaw** [LapisPlugins/HomeSpawn#1]
[22:03:22 INFO]: OnlyBizzclaw issued server command: /listhomes
[22:03:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'listhomes' in net.lapismc.homespawn.commands.HomeSpawnHomeList(homelist)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.lapismc.HomeSpawn.ui.UIDesignerAPI
        at net.lapismc.homespawn.playerdata.HomeSpawnPlayer.showHomesGUI(HomeSpawnPlayer.java:172) ~[?:?]
        at net.lapismc.homespawn.commands.HomeSpawnHomeList.onCommand(HomeSpawnHomeList.java:46) ~[?:?]
        at net.lapismc.homespawn.util.LapisCommand.execute(LapisCommand.java:137) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]

**Comment by OnlyBizzclaw** [comment]
mmm sorry i saw the reason of why

**Comment by Dart2112** [comment]
Out of interest, why did this happen? it seems as though the plugin file was edited.

**Comment by ghost** [comment]
i have the same issue *sad_face*

**Comment by Dart2112** [comment]
@PepijnGamer  The issue you reported to me on spigot has been fixed in an update to HomeSpawnCost

**Comment by OnlyBizzclaw** [comment]
It happens because this plugin is made for 1.12 y used it in 1.8 so the plugin  uses 1.12 sounds

**Comment by Dart2112** [comment]
This has been fixed if you wish to compile the plugin yourself. I will be publishing the update sometime today. It was an issue with the plugin I use for 1.13 compatablilty. It should now work from 1.8 all the way through to 1.13

**Comment by Dart2112** [comment]
> 
> 
> Similar error occurs if using /homelists or /listhome on a 1.13.2 base spigot server. Using /listhomes does not generate the error but also does not present anything in the list. The root cause of the error appears to be a change in the bukkit API:
> 
> Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.BLOCK_NOTE_HAT
> at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_181]
> at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
> at me.kangarko.compatbridge.model.CompSound.parseSound(CompSound.java:80) ~[?:?]
> at me.kangarko.compatbridge.model.CompSound.(CompSound.java:72) ~[?:?]
> at me.kangarko.compatbridge.model.CompSound.(CompSound.java:13) ~[?:?]
> at net.lapismc.HomeSpawn.ui.UIDesignerAPI.(UIDesignerAPI.java:36) ~[?:?]
> at net.lapismc.homespawn.playerdata.HomeSpawnPlayer.showHomesGUI(HomeSpawnPlayer.java:177) ~[?:?]
> at net.lapismc.homespawn.commands.HomeSpawnHomeList.onCommand(HomeSpawnHomeList.java:46) ~[?:?]
> at net.lapismc.homespawn.util.LapisCommand.execute(LapisCommand.java:137) ~[?:?]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]

I have tested the 3.0.5 version on 1.13.2, I don't know if the error was fixed or what but I have not seen that error in my testing
