### ISSUE TITLE
No one can use /spawn or set a spawn and some other commands

### ISSUE THREAD

**Issue by Megalonium** [LapisPlugins/HomeSpawn#12]
Recently I installed the plugin and everything worked nicely but I wanted  to remove the 10 seconds delay for non op player (op player tp instantly). I also modified a bit of the code like permissions and tried to modify the tp delay.
But now almost every commands I try to use just says in the chat that I don't have permission for that and the /sethome tells me I can't have any homes.
Also the server console marks something in red about the config and pvp.
Could you fix that ? Thank you

Here is the config:

# Don't change this value unless you want to reset the config
ConfigVersion: 2

Update:
  # Should updates be automatically downloaded and installed
  Download: false
  # Should console be notified if an update is available, this wont happen if download is true
  NotifyConsole: true

# Should the file watcher be enabled, if true config files will be reloaded when edited
FileWatcher: true

# If true the /setspawn command will also set the world spawn, meaning you will respawn there
SetWorldSpawn: false
# Should the player be respawned at spawn, use this in place of SetWorldSpawn if you dont want spawn chunks at the HomeSpawn spawn
RespawnAtSpawn: false

# If true an inventory based UI will display the players current homes and allow them to teleport
# If false a list of home names will be shown that can be clicked to teleport
HomeListGUI: true

# 0 = cancel teleport, 1 = ignore(this means they will have to keep waiting), 2 = teleport instantly
TeleportCancel: 0
  # PvP means attacked by a player, this could be a direct attack, arrow attack or wolf attack
  PvP: 0
  # Attacked means damaged by a mob
  Attacked: 2
  # Move means they move in the x y or z directions
  Move: 0

# If you want to disable commands you can enter the command names here and they wont be used
# e.g. home would disable the /home command
DisabledCommands:
  - "Command names here"

# Permissions are handled below, there is no limit to how many permissions
# you can have as long as they contain all of the settings
# 0 = false, 1 = true, unless otherwise stated
# (NOTE: in a permission name "," will be replaced with "." EG. homespawn,player = homespawn.player)
Permissions:
  homespawn,player:
    # Who will have this by default? 0=no one 1=everyone 2=OPs
    Default: 1
    # Players will be given the permission with the highest value, if players have multiple permissions.
    Priority: 1
    # How many homes can they have set? 0=none, 1 = no custom names, 1+ is how many homes they can set
    Homes: 1
    # How many seconds must they wait before they are teleported? 0=instant
    TeleportDelay: 0
    # Can they teleport to spawn
    Spawn: 1
    # Can they set the spawn location
    SetSpawn: 2
    # Can they delete spawn
    DeleteSpawn: 2
    # Can they force the plugin to update it's self
    CanUpdate: 2
    # Can they reload the configurations and permissions
    CanReload: 2
    # Can they view player statistics and teleport to other players homes
    CanViewPlayerStats: 2
  homespawn,vip:
    Default: 0
    Priority: 2
    Homes: 5
    TeleportDelay: 0
    Spawn: 1
    SetSpawn: 0
    DeleteSpawn: 0
    CanUpdate: 0
    CanReload: 0
    CanViewPlayerStats: 0
  homespawn,admin:
    Default: 2
    Priority: 3
    Homes: 10
    TeleportDelay: 0
    Spawn: 1
    SetSpawn: 1
    DeleteSpawn: 1
    CanUpdate: 1
    CanReload: 1
    CanViewPlayerStats: 1

-
-
-
-

Here is the error message I've been getting in the console of my server: 

[Server thread/ERROR]: Cannot load plugins/HomeSpawn/config.yml

org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping

in 'reader', line 2, column 1:

ConfigVersion: 2

^

expected <block end>, but found '<block mapping start>'

in 'reader', line 25, column 3:

PvP: 0

^

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:174) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at net.lapismc.homespawn.util.core.LapisCoreConfiguration.checkConfigVersions(LapisCoreConfiguration.java:113) ~[homespawn_14108_534065.jar:?]

at net.lapismc.homespawn.util.core.LapisCoreConfiguration.<init>(LapisCoreConfiguration.java:60) ~[homespawn_14108_534065.jar:?]

at net.lapismc.homespawn.util.core.LapisCoreConfiguration.<init>(LapisCoreConfiguration.java:71) ~[homespawn_14108_534065.jar:?]

at net.lapismc.homespawn.HomeSpawn.onEnable(HomeSpawn.java:50) ~[homespawn_14108_534065.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-318]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-318]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-318]

at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-318]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-318]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-318]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-318]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping

in 'reader', line 2, column 1:

ConfigVersion: 2

^

expected <block end>, but found '<block mapping start>'

in 'reader', line 25, column 3:

PvP: 0

^

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:654) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:319) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]

at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]

at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]

... 21 more

(idk why it says 21 more but I can't see them)

**Comment by Dart2112** [comment]
Unfortunately, the issue you have is that the config.yml file has been malformed, but I can't see why because GitHub doesn't like showing it nicely. Would you please upload the config.yml file in this issue for me so that I can inspect it?

**Comment by Megalonium** [comment]
I belive I can't download the file itself but here it is in .txt
[theconfig.txt](https://github.com/LapisPlugins/HomeSpawn/files/14856770/theconfig.txt)

**Comment by Dart2112** [comment]
The PvP though Move settings had been tabbed over one when they shouldn't have been. Attached is a fixed version.
In future you can use YAML valitation websites to test why the file isnt loading when you see errors in the console.
[theconfig.txt](https://github.com/LapisPlugins/HomeSpawn/files/14856842/theconfig.txt)

**Comment by Megalonium** [comment]
Thank you so much for the fast reply it was that !
