### ISSUE TITLE
/sethome NAME doesnt work

### ISSUE THREAD

**Issue by TheSoulrester** [LapisPlugins/HomeSpawn#2]
while performing this command, i get an error:

```
[18:21:13 INFO]: TheSoulrester issued server command: /sethome new
[18:21:13 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'sethome new' in net.lapismc.homespawn.commands.HomeSpawnSetHome(sethome)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-02518f9]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-02518f9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at net.lapismc.homespawn.HomeSpawnPermissions.loadPermissions(HomeSpawnPermissions.java:52) ~[?:?]
at net.lapismc.homespawn.HomeSpawnPermissions.isPermitted(HomeSpawnPermissions.java:135) ~[?:?]
at net.lapismc.homespawn.util.LapisCommand.isNotPermitted(LapisCommand.java:60) ~[?:?]
at net.lapismc.homespawn.commands.HomeSpawnSetHome.onCommand(HomeSpawnSetHome.java:44) ~[?:?]
at net.lapismc.homespawn.util.LapisCommand.execute(LapisCommand.java:137) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f6a273b-02518f9]
... 14 more
```

**Comment by Dart2112** [comment]
This error has been fixed in 3.0.5 which is live now, Thank you for reporting it
