### ISSUE TITLE
NullPointerException generated when teleporting on delay

### ISSUE THREAD

**Issue by rvause** [LapisPlugins/HomeSpawn#7]
Looks like an exception is being generated [here](https://github.com/LapisPlugins/HomeSpawn/blob/master/src/main/java/net/lapismc/homespawn/playerdata/Home.java#L118).

```
[WARNING] [HomeSpawn] Task #13 for HomeSpawn v3.1.9 generated an exception
java.lang.NullPointerException: null
at net.lapismc.homespawn.playerdata.Home.lambda$teleportPlayer$0(Home.java:120) ~[?:?]
at net.lapismc.homespawn.playerdata.Home$$Lambda$2836.00000000849D77B0.run(Unknown Source) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-ae72bf4-183139d]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212] 
```

Since `cancelTask` method is called in `teleport` it probably makes sense to remove this call. Alternatively it could be wrapped in the same `if (teleportTask != null)` check as other calls to `cancelTask` are.

**Comment by Dart2112** [comment]
I didn't realise they didn't have null checks already, thanks for that.
Updated to include null checks on all instances of TeleportTask#cancelTask()
